HGU-WALAB/hisbee

- src/main/java/com/hcu/hot6/domain/Member.java
- src/main/java/com/hcu/hot6/domain/Mentoring.java
- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/Project.java
- src/main/java/com/hcu/hot6/domain/Study.java
Post를 상속하는 Project, Study, Mentoring 엔티티 작성 및 생성 메소드 구현
> Post entity/#1

- src/main/java/com/hcu/hot6/domain/Member.java
- src/main/java/com/hcu/hot6/domain/Mentoring.java
- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/Project.java
- src/main/java/com/hcu/hot6/domain/Study.java
> :pencil2: [#6] nullable추가 & changeAuthor -> registerAuthor

- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/security/SecurityConfig.java
> [#9] H2 console 허용

- src/main/java/com/hcu/hot6/domain/Mentoring.java
- src/main/java/com/hcu/hot6/domain/Period.java
- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/Project.java
- src/main/java/com/hcu/hot6/domain/Study.java
- src/test/java/com/hcu/hot6/MentoringTest.java
@Setter를 사용하지 않고 @Builder를 사용해서 생성자 구현. 
외부에서 객체를 함부로 수정할 수 없도록 refactoring 진행함. 
Mentoring 객체 생성 테스트 코드 작성 및 테스트 완료. 
Study, Project는 다음 이슈에서 진행할 예정
> B post refactor/#12

- src/main/frontend/src/Routes/Main/Main.tsx
- src/main/frontend/src/Routes/Post/Post.tsx
> 프론트 메인 페이지 디자인/#21

- src/main/java/com/hcu/hot6/domain/Member.java
- src/main/java/com/hcu/hot6/domain/Mentoring.java
- src/main/java/com/hcu/hot6/domain/Period.java
- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/Project.java
- src/main/java/com/hcu/hot6/domain/Study.java
- src/test/java/com/hcu/hot6/MemberTest.java
- src/test/java/com/hcu/hot6/PostTest.java
Mentoring에 구현한 기본 생성자(@Builder), 테스트 코드를 다른 유형과 멤버 클래스에 적용
Post - Project, Study
Member
> B member constructor/#15

- src/main/frontend/src/Routes/SignUp.tsx
- src/main/frontend/src/components/Router.tsx
> F signup 디자인 /#38

- src/main/java/com/hcu/hot6/domain/Mentoring.java
- src/main/java/com/hcu/hot6/domain/Study.java
- `Mentoring.java`
- `Study.java`
업데이트 관련 중복 메서드 제거
> :bug: [#37] 중복 메서드 제거

- src/main/frontend/src/Routes/PostAddForm.tsx
react-hook-form으로 validation 기능 구현 및 state 관리
formar-motion을 이용하여 validation에 애니메이션 삽입
> :sparkles: [#47]모집글 추가 페이지 validation 기능 구현

- src/main/java/com/hcu/hot6/domain/Member.java
- src/main/java/com/hcu/hot6/domain/request/PostCreationRequest.java
- src/test/java/com/hcu/hot6/PostApiTest.java
스프링 시큐리티 환경에서 테스트 코드가 동작할 수 있도록 개선함.
- 모집글 유효성 검사: 필수 입력 정보 미기입, 과거 날짜, 음수 모집 인원
- 모집글 생성, 조회, 수정, 삭제
resolved: #39
> 모집글 관련 통합 테스트 리팩토링

- src/main/frontend/package-lock.json
- src/main/frontend/package.json
- src/main/frontend/public/index.html
- src/main/frontend/src/Routes/Detail.tsx
- src/main/frontend/src/Routes/Main.tsx
- src/main/frontend/src/Routes/Post.tsx
- src/main/frontend/src/Routes/Profile.tsx
- src/main/frontend/src/api.tsx
- src/main/frontend/src/components/Router.tsx
> 마이페이지 제작 + 모집글 수정 /#51

- src/main/frontend/src/Routes/Detail.tsx
- src/main/frontend/src/Routes/PostAddForm.tsx
- src/main/frontend/src/Routes/Profile.tsx
- src/main/frontend/src/Routes/SignUp.tsx
- src/main/frontend/src/Routes/SignUpOptional.tsx
- src/main/frontend/src/api.tsx
- src/main/frontend/src/components/Router.tsx
백엔드 시온 코드 수정한 부분
- department ,  position (enum) 한글로 수정
- grade number -> string으로 수정
+ 해줬으면 하는 일
- put을 해줄 때 필드들이 required 라고 뜸
> api들 연결 + 백엔드 시온 코드 수정 /#66

- src/main/frontend/src/Routes/Login.tsx
- src/main/frontend/src/Routes/Profile.tsx
- src/main/frontend/src/api.tsx
- src/main/java/com/hcu/hot6/domain/Department.java
- src/main/java/com/hcu/hot6/domain/Member.java
- src/main/java/com/hcu/hot6/domain/Position.java
- src/main/java/com/hcu/hot6/domain/request/MemberRequest.java
- src/main/java/com/hcu/hot6/domain/response/MemberProfileResponse.java
백엔드 시온 코드 수정한 부분
- department ,  position (enum) 한글로 수정
- grade number -> string으로 수정
+ 해줬으면 하는 일
- put을 해줄 때 필드들이 required 라고 뜸
> :bug: [#66] put api 연결 도중 백엔드 에러 발견 및 수정

- src/main/java/com/hcu/hot6/config/QueryDSLConfig.java
- src/main/java/com/hcu/hot6/repository/PoolRepository.java
- src/main/java/com/hcu/hot6/service/MemberService.java
- src/test/java/com/hcu/hot6/repository/PoolRepositoryTest.java
`JPAQuery<?>` -> `JpaQueryFactory`
> :bug: [#75] 조회가 잘 안되는 버그 수정

- src/main/java/com/hcu/hot6/PostApiController.java
- src/main/java/com/hcu/hot6/controller/ExceptionController.java
- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/service/PostService.java
- src/test/java/com/hcu/hot6/PostApiTest.java
- 모집글 찜/삭제 지원: `/posts/:postId/likes`
> 모집글 찜 추가/삭제

- src/main/java/com/hcu/hot6/domain/Mentoring.java
- src/main/java/com/hcu/hot6/domain/response/PostReadOneResponse.java
- 멘토링 모집글 생성시 보수 유무가 적용되지 않는 버그 수정
- 조회 결과 응답시 보수 유무 값이 동기화 되지 않는 버그 수정
> 모집글 보수 유무 결과가 반영되지 않는 버그 수정

- src/main/frontend/src/Routes/BlankPage.tsx
- src/main/frontend/src/Routes/Detail.tsx
- src/main/frontend/src/Routes/Main.tsx
- src/main/frontend/src/Routes/Person.tsx
- src/main/frontend/src/Routes/Profile.tsx
- src/main/frontend/src/Routes/SignUp.tsx
- src/main/frontend/src/api.tsx
- src/main/frontend/src/components/LoadingAnimation.tsx
- src/main/frontend/src/components/Router.tsx
토큰, isRegistered 빈 페이지에서 받게 하기
최초 로그인 일 때만 회원가입 폼으로 이동.
인재풀 통해서 상대 프로필 Link 통해서 볼 수 있게 만들기
페이지 상세 보기 isMine 필드로 자신의 글인지 확인
찜 api 연결 코드 작성
> 유저 상황 별 설정 /#96

- src/main/frontend/src/Routes/Person.tsx
- src/main/frontend/src/Routes/Profile.tsx
- src/main/frontend/src/components/DeleteModal.tsx
- src/main/frontend/src/components/Footer.tsx
- src/main/frontend/src/components/Header.tsx
- src/main/frontend/src/components/LoadingAnimation.tsx
- src/main/frontend/src/components/LoginModal.tsx
- src/main/frontend/src/components/PostDeleteModal.tsx
Footer 애니메이션 적용
로그인 폼 , 삭제 폼 , 수정 폼 애니메이션 적용
Nav 부분 애니메이션 수정
Loading 디자인 수정
paging 디자인 수정
> 애니메이션 + 디자인 완료 /#102

- src/main/java/com/hcu/hot6/PostApiController.java
- src/main/java/com/hcu/hot6/domain/Mentoring.java
- src/main/java/com/hcu/hot6/domain/Pagination.java
- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/Project.java
- src/main/java/com/hcu/hot6/domain/Study.java
- src/main/java/com/hcu/hot6/domain/converter/OrderByConverter.java
- src/main/java/com/hcu/hot6/domain/converter/PostTypeConverter.java
- src/main/java/com/hcu/hot6/domain/converter/PostTypeDetailsConverter.java
- src/main/java/com/hcu/hot6/domain/enums/OrderBy.java
- src/main/java/com/hcu/hot6/domain/enums/PostType.java
- src/main/java/com/hcu/hot6/domain/enums/PostTypeDetails.java
- src/main/java/com/hcu/hot6/domain/filter/PostSearchFilter.java
- src/main/java/com/hcu/hot6/domain/response/PostReadOneResponse.java
- src/main/java/com/hcu/hot6/repository/PostRepository.java
- src/main/java/com/hcu/hot6/service/PostService.java
- 페이지
- 제목 검색
- 정렬
- 모집글 유형
- 보수 유무
- 불러올 데이터 개수 제한
- 모집글을 불러올 때 응답폼에 쿼리 결과를 바인딩하는 과정에서 잘못된 프로퍼티가 할당된 오류 수정
> 모집글 필터링 기능

- src/main/java/com/hcu/hot6/domain/Member.java
탈퇴 처리를 요청하는 회원의 작성 모집글이 있는 경우 탈퇴 처리가 안되던 버그 수정
> :bug: 작성 모집글이 있는 회원 탈퇴처리

- src/main/frontend/src/Routes/Main.tsx
- src/main/frontend/src/Routes/Person.tsx
- src/main/frontend/src/Routes/Post.tsx
- src/main/frontend/src/Routes/PostAddForm.tsx
- src/main/frontend/src/api.tsx
- src/main/frontend/src/components/PostDeleteModal.tsx
api total 필드 추가에 따른 버그 수정과 pagenation 버그 수정
> api 필드 추가에 따른 버그 수정 /#106

- build.gradle
- src/main/java/com/hcu/hot6/domain/request/PostCreationRequest.java
- src/main/java/com/hcu/hot6/domain/response/MemberPoolResponse.java
- src/main/java/com/hcu/hot6/repository/PoolRepository.java
- src/main/java/com/hcu/hot6/service/MemberService.java
- src/test/java/com/hcu/hot6/PostApiTest.java
> 순환 참조 버그 수정

- src/main/java/com/hcu/hot6/domain/Member.java
- src/main/java/com/hcu/hot6/domain/request/MemberRequest.java
- src/main/java/com/hcu/hot6/domain/response/MemberProfileResponse.java
- src/test/java/com/hcu/hot6/controller/MemberControllerTest.java
- src/test/java/com/hcu/hot6/controller/PostControllerTest.java
Name | Type | Description | Required
-- | -- | -- | --
pictureUrl | String | 프로필 사진 경로 | X
resolved: #123
> 프로필 이미지 수정

- src/main/frontend/src/Routes/Detail.tsx
- src/main/frontend/src/Routes/Main.tsx
- src/main/frontend/src/Routes/Post.tsx
- src/main/frontend/src/Routes/PostAddForm.tsx
- src/main/frontend/src/Routes/SignUpOptional.tsx
> 반응형 완성/#106

- src/main/java/com/hcu/hot6/controller/PostApiController.java
- src/main/java/com/hcu/hot6/domain/Archive.java
- src/main/java/com/hcu/hot6/domain/Bookmark.java
- src/main/java/com/hcu/hot6/domain/Keyword.java
- src/main/java/com/hcu/hot6/domain/Member.java
- src/main/java/com/hcu/hot6/domain/Position.java
- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/Poster.java
- src/main/java/com/hcu/hot6/domain/Thumbnail.java
- src/main/java/com/hcu/hot6/domain/response/KeywordSearchedResponse.java
- src/main/java/com/hcu/hot6/repository/PostRepository.java
- src/main/java/com/hcu/hot6/service/PostService.java
- src/test/java/com/hcu/hot6/PostTest.java
- src/test/java/com/hcu/hot6/controller/PostControllerTest.java
> :sparkles: [#134] version2 엔티티 수정

- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/response/PostReadOneResponse.java
thumbnail, position, poster 등의 클래스 추가, 엔티티 변경에 따라 readOne의 response 수정함.
> :sparkles: [#141] readOne API 수정

- src/main/java/com/hcu/hot6/controller/PostApiController.java
- src/main/java/com/hcu/hot6/domain/Keyword.java
- src/main/java/com/hcu/hot6/repository/KeywordRepository.java
- src/main/java/com/hcu/hot6/service/KeywordService.java
> :sparkles: [#143] 모집글 생성시 키워드 저장

- src/main/java/com/hcu/hot6/repository/PostRepository.java
> :pencil2: [#150] bookmarks -> likes로 변경

- src/main/frontend/src/Routes/Detail/Detail2.tsx
- src/main/frontend/src/Routes/Post/Post.tsx
- src/main/frontend/src/Routes/PostAddForm/PostAddForm2.tsx
- src/main/frontend/src/Routes/PostAddForm/PostExamples.ts
- src/main/frontend/src/Routes/PostAddForm/textarea.css
- src/main/frontend/src/api.tsx
모집글 작성페이지 4.6일 피드백 반영
- duration 추가
- 펼치고 선택사항 구분
> 모집글 작성페이지 4.6일 피드백 반영 업데이트 , 모집글 상세보기 페이지 /#148

- src/main/java/com/hcu/hot6/domain/Post.java
255(2^8 - 1) 바이트 -> 4095(2^12 - 1) 바이트
한글 기준으로 약 1500자 + 이모지까지 담을 수 있을 것으로 추정.
> :ambulance: 모집글 상세 내용 크기 설정

- src/main/java/com/hcu/hot6/domain/response/PostThumbnailResponse.java
- src/main/java/com/hcu/hot6/service/PostService.java
isClosed, nLike 반환 필드 추가 및 아카이빙된 모집글 썸네일은 반환X
> :recycle: [#160] 아카이빙 된 모집글 필터링 response에서 제외

- src/main/java/com/hcu/hot6/controller/PostApiController.java
- src/main/java/com/hcu/hot6/domain/Likes.java
- src/main/java/com/hcu/hot6/domain/response/LikesResponse.java
- src/main/java/com/hcu/hot6/repository/LikesRepository.java
- src/main/java/com/hcu/hot6/service/PostService.java
> :sparkles: [#160] 북마크 생성 구현

- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/Poster.java
- src/main/java/com/hcu/hot6/domain/request/PostUpdateRequest.java
생성 시 CascadeType.ALL, 참조 삭제 시 orphanRemoval = true
> :sparkles: [#160] poster path 생성, 수정 구현

- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/request/PostUpdateRequest.java
- src/main/java/com/hcu/hot6/domain/response/PostReadOneResponse.java
> :recycle: [#160] posterPath 참조 X, string 콤마 구분으로 변경

- src/main/java/com/hcu/hot6/controller/PostApiController.java
- src/main/java/com/hcu/hot6/domain/Archive.java
- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/Thumbnail.java
- src/main/java/com/hcu/hot6/domain/request/MemberRequest.java
- src/main/java/com/hcu/hot6/domain/request/PostUpdateRequest.java
- src/main/java/com/hcu/hot6/domain/response/ArchiveResponse.java
- src/main/java/com/hcu/hot6/domain/response/PostReadOneResponse.java
- src/main/java/com/hcu/hot6/repository/PostRepository.java
- src/main/java/com/hcu/hot6/service/PostService.java
- src/test/java/com/hcu/hot6/post/PostArchiveTests.java
- src/test/java/com/hcu/hot6/post/PostFilterTests.java
- src/test/java/com/hcu/hot6/post/PostUpdateTests.java
> 모집글 아카이브(보관) 기능 추가

- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/response/PostReadOneResponse.java
String 콤마 구분이 아닌 Poster 엔티티 사용으로 다시 변경함.
> :recycle: [#160] posterPaths create, update 구현 완료

- src/main/java/com/hcu/hot6/controller/PostApiController.java
- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/Thumbnail.java
- src/main/java/com/hcu/hot6/domain/response/PostReadOneResponse.java
- src/main/java/com/hcu/hot6/service/PostService.java
> :recycle: [#160] nullable한 필드 빈 값이 아니라 null이 들어가도록 수정

- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/Poster.java
- src/main/java/com/hcu/hot6/domain/request/TagForm.java
- src/main/java/com/hcu/hot6/domain/response/PostReadOneResponse.java
- src/main/java/com/hcu/hot6/util/Utils.java
- src/test/java/com/hcu/hot6/post/PostReadTests.java
> 모집글 포스터 경로 저장 

- src/main/java/com/hcu/hot6/domain/Department.java
- src/main/java/com/hcu/hot6/domain/Member.java
- src/main/java/com/hcu/hot6/domain/enums/Major.java
- src/main/java/com/hcu/hot6/domain/request/MemberRequest.java
- src/main/java/com/hcu/hot6/domain/request/PostCreationRequest.java
- src/main/java/com/hcu/hot6/domain/response/MemberProfileResponse.java
- src/main/java/com/hcu/hot6/domain/response/MemberResponse.java
- src/main/java/com/hcu/hot6/repository/PostRepository.java
- src/test/java/com/hcu/hot6/member/MemberProfileTests.java
- src/test/java/com/hcu/hot6/post/PostArchiveTests.java
- src/test/java/com/hcu/hot6/post/PostFilterTests.java
- src/test/java/com/hcu/hot6/post/PostReadTests.java
- src/test/java/com/hcu/hot6/post/PostUpdateTests.java
> 유저 프로필 생성/조회 

- src/main/java/com/hcu/hot6/repository/PostRepository.java
- src/test/java/com/hcu/hot6/post/PostFilterTests.java
> :sparkles: [#189] 내 전공 필터링 구현

- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/request/PostCreationRequest.java
- src/main/java/com/hcu/hot6/repository/PostRepository.java
- src/test/java/com/hcu/hot6/post/PostFilterTests.java
> :sparkles: [#189] 기타 모집글 필터링 구현 완료

- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/request/PostUpdateRequest.java
- src/test/java/com/hcu/hot6/post/PostFilterTests.java
> :recycle: [#189] 기타 여부 수정 시 모집글 필터링

- src/main/java/com/hcu/hot6/domain/response/PostReadOneResponse.java
- src/main/java/com/hcu/hot6/repository/PostRepository.java
> :bug: 학년필터링 버그 수정, post read시 isETC반환

- src/main/frontend/package-lock.json
- src/main/frontend/package.json
- src/main/frontend/src/Routes/Post/Post.tsx
- src/main/frontend/src/Routes/PostAddForm/PostAddForm2.tsx
- src/main/frontend/src/api.tsx
- src/main/frontend/src/index.tsx
rest api 
.env 파일에 환경변수 추가
환경 변수 사용 api.tsx파일
localhost:8080/posts?Limit=1&page=1 -> ${precess.env.REACT_APP_BACK_BASE_URL}/posts?Limit=1&page=1
> baseurl 환경 변수 설정/#196

- src/main/frontend/src/Routes/Detail/Detail2.tsx
- src/main/frontend/src/Routes/Main/SignUp2.tsx
- src/main/frontend/src/Routes/Main/UserProfileInputs.tsx
- src/main/frontend/src/Routes/PostAddForm/PostAddForm2.tsx
major 1 , major 2 state 변경 인식 못함 버그 수정
> :bug: [#196]signup

- src/main/frontend/src/components/LoginModal.tsx
> :bug: [#196]환경 변수 버그 수정

- src/main/frontend/.env.development
- src/main/frontend/.env.production
- src/main/frontend/src/components/Header.tsx
> :bug: [#196]env파일 이름 수정

- src/main/java/com/hcu/hot6/config/SecurityConfig.java
- src/main/java/com/hcu/hot6/controller/KeywordController.java
- src/main/java/com/hcu/hot6/controller/PostApiController.java
- src/main/java/com/hcu/hot6/domain/Archive.java
- src/main/java/com/hcu/hot6/domain/Keyword.java
- src/main/java/com/hcu/hot6/domain/Post.java
- src/main/java/com/hcu/hot6/domain/PostKeyword.java
- src/main/java/com/hcu/hot6/repository/KeywordRepository.java
- src/main/java/com/hcu/hot6/repository/PostKeywordRepository.java
- src/main/java/com/hcu/hot6/service/KeywordService.java
- src/main/java/com/hcu/hot6/service/PostService.java
- src/test/java/com/hcu/hot6/keyword/KeywordSuggestTest.java
- src/test/java/com/hcu/hot6/member/MemberProfileTests.java
- src/test/java/com/hcu/hot6/post/PostReadTests.java
유저가 입력한 키워드 목록에 기반하여 해당 키워드를 포함하는 모집글에 사용된 키워드 중 사용 횟수(frequency) 가 높은 순으로 정렬하여 상위 10개 제공
> 관련 키워드 추천 

- src/main/frontend/package-lock.json
- src/main/java/com/hcu/hot6/controller/KeywordController.java
- src/main/java/com/hcu/hot6/domain/request/TagForm.java
- src/main/java/com/hcu/hot6/repository/KeywordRepository.java
- src/main/java/com/hcu/hot6/service/KeywordService.java
- src/test/java/com/hcu/hot6/keyword/KeywordTest.java
> :sparkles: 키워드 자동완성

- src/main/frontend/src/Routes/Detail/Detail2.tsx
- src/main/frontend/src/Routes/Post/Post.tsx
- src/main/frontend/src/Routes/PostAddForm/PostAddForm2.tsx
- src/main/frontend/src/Routes/PostAddForm/components/Duration.tsx
- src/main/frontend/src/Routes/PostAddForm/components/Keywords.tsx
- src/main/frontend/src/Routes/PostAddForm/components/People.tsx
- src/main/frontend/src/Routes/PostAddForm/components/PostExamples.ts
- src/main/frontend/src/Routes/PostAddForm/css/textarea.css
- src/main/frontend/src/Routes/PostModifyForm/PostModifyForm.tsx
- src/main/frontend/src/Routes/PostModifyForm/components/People.tsx
- src/main/frontend/src/components/Router.tsx
- src/main/java/com/hcu/hot6/domain/request/PostCreationRequest.java
- src/main/java/com/hcu/hot6/domain/request/PostUpdateRequest.java
카테고리가 축소 됨에 따라 모집글 작성 / 수정 폼에 변화가 생긴다.
그리고 메인 페이지에서의 필터링에도 카테고리에 변동이 생긴다.
기존 카테고리 : 전체 , 동아리 , 학회 , 공모전/대회 , 스터디 , 프로젝트 , 학술모임 , 운동/게임/취미 , 기타
변경 카테고리 : 수업 내 프로젝트 , 자율 프로젝트
이슈 번호
#258 
1. 수정 폼과 생성 폼이 분리 되어 있어서 하나의 페이지로 합치는 작업을 진행하였음.
2. warning을 삭제하여 터미널을 좀 더 클린하게 관리
3. input 태그를 모두 MUI TextField + Controller로 대체하였음.
> FIX : 카테고리가 변경됨에 따른 프론트 수정 적용

- src/main/frontend/src/Routes/PostAddForm/PostAddForm2.tsx
모집글을 작성할 때 하단에 모임과 관련된 키워드를 입력하게 되는데,
거기서 이미 등록된 키워드 목록을 클릭하면 자동으로 모집글이 등록됩니다. (심지어 제목이 없어도)
모집글 작성 버튼 클릭
하단 "모임과 관련된 키워드를 입력하여 검색 결과에 노출될 수 있게 해보세요!" 메뉴에서 뜨는 키워드 아무거나 클릭
게시글이 자동으로 작성완료 처리됨
모집글을 작성할 때 엔터를 통해 모집글이 작성되는 버그가 있었음.
엔터를 통해 모집글이 작성이 진행 되는 버그를 차단하였음.
> HOTFIX : 검색 키워드 클릭시 게시글이 작성완료되는 버그 수정(#261)

- src/main/frontend/src/Routes/PostAddForm/components/PostExamples.ts
게시글을 작성할 때 상시모집을 선택하고 작성 완료하면 메인페이지에서 "모집마감"으로 표시됩니다.
이슈 1) 게시글 작성 시 상시 모집 선택 -> 모집 마감으로 뜸
이슈 2) 게시판에서 상시 모집인 글 -> 모집 마감으로 뜸
상시 모집 시 모집 마감으로 뜨지 않도록 버그 수정
#260
> Fix: 게시글 작성에서 상시모집 선택시 모집마감으로 표시되는 버그 (#260)

- src/main/frontend/src/components/Footer.tsx
Footer Contact 부분에 설문 참여 링크 첨부
> Feat: 설문 참여 링크 첨부(#264)
